### ISSUE TITLE
Nefunguje prehravanie niektorych videi

### ISSUE THREAD

**Issue by ghost** [kodi-czsk/plugin.video.sledujufilmy.cz#1]
Ahoj, dnes som si skusil pustit MASH serial ale prehralo mi to iba 1. epizodu z 1. serie, skusal som zopar dalsich (2. a 3. epizodu) ale pise mi to Playback failed. 
Raspberry Pi type B, OSMC 2015.06-1 (kernel: Linux 3.18.13-1-osmc) (Compiled: May 23 2015)
Dalo by sa s tym moc pekne prosim nieco urobit? Vdaka!
Log: 

> NOTICE: -->Python Interpreter Initialized<--
> NOTICE: ["Initializing provider sledujufilmy.cz with settings {'downloads': '/media/Lukas/', 'quality': '0'}"]
> NOTICE: [u'Found resolvable http://youwatch.org/embed-0i261tpwwlna-550x470.html']
> NOTICE: [u'Resolving http://youwatch.org/embed-0i261tpwwlna-550x470.html']
> NOTICE: ["Using resolver 'youwatch'"]
> NOTICE: Reporting for plugin.video.sledujufilmy.cz disabled by user
> NOTICE: Sending http://fs39.youwatch.org:8777/r7vpxqp4gooax3ptx3mipbpb66du4ncin2cgee7khpi3uradjxifzvlgza/video.mp4 to player
> NOTICE: DVDPlayer: Opening: http://fs39.youwatch.org:8777/r7vpxqp4gooax3ptx3mipbpb66du4ncin2cgee7khpi3uradjxifzvlgza/video.mp4
> WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
> NOTICE: Thread DVDPlayer start, auto delete: false
> NOTICE: Creating InputStream
> NOTICE: Thread CMMALRenderer start, auto delete: false
> ERROR: CCurlFile::Stat - Failed: Timeout was reached(28) for http://fs39.youwatch.org:8777/r7vpxqp4gooax3ptx3mipbpb66du4ncin2cgee7khpi3uradjxifzvlgza/video.mp4
> ERROR: CCurlFile::FillBuffer - Failed: Timeout was reached(28)
> ERROR: CCurlFile::CReadState::Connect, didn't get any data from stream.
> ERROR: Open - failed to open source http://fs39.youwatch.org:8777/r7vpxqp4gooax3ptx3mipbpb66du4ncin2cgee7khpi3uradjxifzvlgza/video.mp4
> ERROR: CDVDPlayer::OpenInputStream - error opening [http://fs39.youwatch.org:8777/r7vpxqp4gooax3ptx3mipbpb66du4ncin2cgee7khpi3uradjxifzvlgza/video.mp4]
> NOTICE: CDVDPlayer::OnExit()
> ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.sledujufilmy.cz/?play=687474703a2f2f73657269616c792e736c6564756a7566696c6d792e637a2f6d6173682f312d73657269652f30317830322d68656e72792d70726f73696d2d767261742d73652d646f6d752f&cp=736c6564756a7566696c6d792e637a&]
> NOTICE: CDVDPlayer::CloseFile()
> NOTICE: DVDPlayer: waiting for threads to exit

**Comment by lubo** [comment]
Ahoj @badyto, vdaka za nahlasenie problemu. Problem bude opraveny v dalsej verzii stream resolveru. Aktualny stav mozes sledovat na kodi-czsk/script.module.stream.resolver#23.
